import { useEffect, useState, type FormEvent } from 'react'
import { ArrowRight, CalendarDays, Check, Clock3, Plus, Settings2, Users, X } from 'lucide-react'
import './admin.css'

type Service={id:number;name:string;description:string;duration_minutes:number;price:number|string;active?:boolean}
type Provider={id:number;name:string;bio:string;active:boolean;service_ids:number[]}
type Booking={id:number;service_id:number;provider_id:number;customer_id?:number;starts_at:string;ends_at:string;status:string;price_at_booking:number|string}
type Props={api:string;token:string;onClose:()=>void}
const weekdays=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday']
const cash=(n:number|string)=>new Intl.NumberFormat('uz-UZ').format(Number(n))+' so‘m'
const time=(x:string)=>new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Tashkent',weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(x))

export default function AdminDashboard({api,token,onClose}:Props){
  const [tab,setTab]=useState<'bookings'|'services'|'team'|'hours'>('bookings')
  const [services,setServices]=useState<Service[]>([])
  const [providers,setProviders]=useState<Provider[]>([])
  const [bookings,setBookings]=useState<Booking[]>([])
  const [loading,setLoading]=useState(true)
  const [message,setMessage]=useState('')
  const [busy,setBusy]=useState(false)
  const headers={'Authorization':`Bearer ${token}`}
  const reload=async()=>{setLoading(true);try{const [s,p,b]=await Promise.all([fetch(`${api}/api/services`),fetch(`${api}/api/providers`),fetch(`${api}/api/bookings`,{headers})]);if(!s.ok||!p.ok||!b.ok)throw new Error('Could not load dashboard data');setServices(await s.json());setProviders(await p.json());setBookings(await b.json())}catch(e){setMessage(e instanceof Error?e.message:'Could not load dashboard')}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[])
  async function submit(e:FormEvent<HTMLFormElement>,path:string,success:string){e.preventDefault();const formElement=e.currentTarget;const form=new FormData(formElement);const payload=Object.fromEntries(form.entries());setBusy(true);setMessage('');try{const r=await fetch(`${api}${path}`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){const info=await r.json();throw new Error(info.detail||'Could not save changes')};setMessage(success);formElement.reset();await reload()}catch(err){setMessage(err instanceof Error?err.message:'Could not save changes')}finally{setBusy(false)}}
  async function createProvider(e:FormEvent<HTMLFormElement>){e.preventDefault();const formElement=e.currentTarget;const f=new FormData(formElement);const ids=f.getAll('service_ids').map(Number);setBusy(true);try{const r=await fetch(`${api}/api/providers`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),bio:f.get('bio'),service_ids:ids})});if(!r.ok)throw new Error((await r.json()).detail||'Could not add team member');setMessage('Your new team member is ready.');formElement.reset();await reload()}catch(err){setMessage(err instanceof Error?err.message:'Could not add team member')}finally{setBusy(false)}}
  async function status(item:Booking,next:string){setBusy(true);try{const r=await fetch(`${api}/api/bookings/${item.id}/status`,{method:'PATCH',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({status:next})});if(!r.ok)throw new Error((await r.json()).detail||'Could not update booking');setMessage(`Booking #${item.id} is now ${next}.`);await reload()}catch(err){setMessage(err instanceof Error?err.message:'Could not update booking')}finally{setBusy(false)}}
  const nav=[['bookings','Bookings',CalendarDays],['services','Services',Settings2],['team','Your team',Users],['hours','Availability',Clock3]] as const
  return <div className="admin-overlay"><aside className="admin-shell"><header className="admin-header"><a className="brand" href="#top"><span className="brand-icon">s.</span>sana<span className="brand-dot">.</span><span className="admin-label">STUDIO ADMIN</span></a><button className="admin-close" onClick={onClose}><span>Back to site</span><X size={17}/></button></header><div className="admin-layout"><nav className="admin-nav"><div className="admin-nav-title">YOUR STUDIO</div>{nav.map(([key,label,Icon])=><button key={key} className={tab===key?'admin-nav-active':''} onClick={()=>{setTab(key);setMessage('')}}><Icon size={16}/>{label}<ArrowRight size={13}/></button>)}<div className="admin-nav-note"><span><Check size={14}/></span><div><b>Looking lovely.</b><small>Your studio, your rhythm.</small></div></div></nav><main className="admin-main"><div className="admin-title"><div><div className="eyebrow"><span className="eyebrow-line"/> YOUR BUSINESS, AT A GLANCE</div><h1>{nav.find(n=>n[0]===tab)?.[1]}<span className="brand-dot">.</span></h1></div><button className="admin-refresh" onClick={()=>void reload()}>Refresh <ArrowRight size={14}/></button></div>{message&&<div className="admin-message">{message}</div>}{loading?<div className="admin-loading">Getting your studio ready…</div>:<>
    {tab==='bookings'&&<><div className="admin-summary"><div><span>ALL APPOINTMENTS</span><b>{bookings.length}</b></div><div><span>NEED YOUR OK</span><b>{bookings.filter(b=>b.status==='pending').length}</b></div><div><span>CONFIRMED</span><b>{bookings.filter(b=>b.status==='confirmed').length}</b></div></div><div className="admin-list-head"><b>Every appointment</b><span>Review, confirm or update the visit.</span></div>{bookings.length===0?<div className="admin-blank">No bookings just yet. They’ll find their way here.</div>:<div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>GUEST / SERVICE</th><th>WHEN</th><th>STATUS</th><th>AMOUNT</th><th>ACTION</th></tr></thead><tbody>{bookings.map(b=>{const s=services.find(x=>x.id===b.service_id);const p=providers.find(x=>x.id===b.provider_id);return <tr key={b.id}><td><b>{s?.name||`Service #${b.service_id}`}</b><small>{p?.name||`Provider #${b.provider_id}`} · guest #{b.customer_id||'—'}</small></td><td>{time(b.starts_at)}</td><td><span className={`admin-status status-${b.status}`}>{b.status}</span></td><td>{cash(b.price_at_booking)}</td><td><div className="admin-actions">{b.status==='pending'&&<button disabled={busy} onClick={()=>void status(b,'confirmed')}>Confirm</button>}{b.status==='confirmed'&&<button disabled={busy} onClick={()=>void status(b,'completed')}>Complete</button>}{['pending','confirmed'].includes(b.status)&&<button className="admin-cancel" disabled={busy} onClick={()=>void status(b,'cancelled')}>Cancel</button>}</div></td></tr>})}</tbody></table></div>}</>}
    {tab==='services'&&<div className="admin-columns"><div className="admin-form-card"><span className="mini-label">ADD SOMETHING GOOD</span><h2>New service</h2><form onSubmit={e=>void submit(e,'/api/services','Service added to your menu.')}><label>Service name<input required name="name" placeholder="e.g. Signature haircut"/></label><label>Description<textarea name="description" rows={3} placeholder="What makes this one special?"/></label><div className="admin-form-row"><label>Duration (minutes)<input required type="number" name="duration_minutes" min="1" max="480" defaultValue="45"/></label><label>Price (UZS)<input required type="number" name="price" min="0" step="0.01" placeholder="180000"/></label></div><button className="admin-submit" disabled={busy}><Plus size={15}/> Add service</button></form></div><div className="admin-catalog"><span className="mini-label">ON THE MENU</span><h2>Your services <span>{services.length}</span></h2>{services.map(s=><article key={s.id} className="admin-item"><span className="admin-item-icon">✳</span><div><b>{s.name}</b><small>{s.duration_minutes} minutes · {cash(s.price)}</small></div><span className="item-live">LIVE</span></article>)}</div></div>}
    {tab==='team'&&<div className="admin-columns"><div className="admin-form-card"><span className="mini-label">GOOD PEOPLE, GOOD CARE</span><h2>Add a teammate</h2><form onSubmit={e=>void createProvider(e)}><label>Name<input required name="name" placeholder="e.g. Malika R."/></label><label>A little about them<textarea name="bio" rows={3} placeholder="Their specialty, their style…"/></label><fieldset className="service-checks"><legend>Services they offer</legend>{services.map(s=><label key={s.id}><input type="checkbox" name="service_ids" value={s.id}/><span>{s.name}</span></label>)}</fieldset><button className="admin-submit" disabled={busy}><Plus size={15}/> Add teammate</button></form></div><div className="admin-catalog"><span className="mini-label">THE PEOPLE BEHIND THE GOOD</span><h2>Your team <span>{providers.length}</span></h2>{providers.map((p,i)=><article key={p.id} className="admin-item"><span className={`provider-avatar tone-${i%3}`}>{p.name.split(' ').map(c=>c[0]).slice(0,2).join('')}</span><div><b>{p.name}</b><small>{p.bio||'Sana team member'} · {(p.service_ids||[]).length} services</small></div><span className="item-live">ACTIVE</span></article>)}</div></div>}
    {tab==='hours'&&<div className="admin-columns"><div className="admin-form-card"><span className="mini-label">MAKE ROOM FOR GOOD</span><h2>Set weekly hours</h2><p className="admin-help">Availability repeats each week in Tashkent time. Customers can book in 15-minute increments.</p><form onSubmit={e=>void submit(e,`/api/providers/${new FormData(e.currentTarget).get('provider_id')}/availability`,'Weekly availability saved.')}><label>Team member<select name="provider_id" required defaultValue="">{providers.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Day of week<select name="weekday" defaultValue="0">{weekdays.map((d,i)=><option key={d} value={i}>{d}</option>)}</select></label><div className="admin-form-row"><label>From<input type="time" name="starts_at" required defaultValue="09:00"/></label><label>Until<input type="time" name="ends_at" required defaultValue="17:00"/></label></div><input type="hidden" name="timezone" value="Asia/Tashkent"/><button className="admin-submit" disabled={busy||providers.length===0}><Plus size={15}/> Save hours</button>{providers.length===0&&<small className="form-hint">Add a teammate before setting hours.</small>}</form></div><div className="admin-catalog"><span className="mini-label">CURRENTLY BOOKABLE</span><h2>Availability rules</h2>{providers.map(p=><article className="admin-item" key={p.id}><span className="provider-avatar">{p.name.split(' ').map(c=>c[0]).slice(0,2).join('')}</span><div><b>{p.name}</b><small>Weekly schedule · Asia/Tashkent</small></div></article>)}</div></div>}
  </>}</main></div></aside></div>
}
