import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { Armchair, CalendarDays, Check, Clock3, Film, MapPin, Moon, Search, ShieldCheck, Sun, Ticket, UserRound, X } from 'lucide-react'

type Movie={id:number;title:string;synopsis:string;duration_minutes:number|null;genre:string;age_rating:string;language:string;poster_url:string;backdrop_url?:string;release_date?:string|null;vote_average?:number|null;cast_names?:string[];trailer_key?:string|null;catalog_status?:string;active?:boolean}
type Screening={id:number;movie_id:number;starts_at:string;ends_at:string;base_price:number|string;premium_surcharge:number|string;movie_title:string;duration_minutes:number;cinema_name:string;auditorium_name:string;timezone:string;available_seats:number;format_type:string}
type Seat={id:number;row_label:string;seat_number:number;seat_type:string;price:number|string;available:boolean}
type Booking={id:number;status:string;seat_count:number;total_price:number|string;hold_expires_at:string|null;created_at:string;movie_title:string;starts_at:string;cinema_name:string;auditorium_name:string;seats:string[]}
type User={id:number;name:string;nickname:string;email:string;role:string}
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'')
const tz='Asia/Tashkent'
const money=(n:number|string)=>`${new Intl.NumberFormat('uz-UZ').format(Number(n))} so'm`
const dateKey=(d:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'}).format(d)
const today=dateKey(new Date())
const days=Array.from({length:7},(_,i)=>{const d=new Date(`${today}T12:00:00+05:00`);d.setUTCDate(d.getUTCDate()+i);return dateKey(d)})
const stamp=(iso:string,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat('uz-UZ',{...options,timeZone:tz}).format(new Date(iso))
const authHeaders=(token:string)=>({Authorization:`Bearer ${token}`,'Content-Type':'application/json'})

export default function App(){
 const [theme,setTheme]=useState<'light'|'dark'>(()=>localStorage.getItem('parda_theme')==='dark'?'dark':'light')
 const [movies,setMovies]=useState<Movie[]>([]),[category,setCategory]=useState<'now_playing'|'upcoming'>('now_playing')
 const [screenings,setScreenings]=useState<Screening[]>([]),[day,setDay]=useState(today),[query,setQuery]=useState('')
 const [user,setUser]=useState<User|null>(null),[token,setToken]=useState(localStorage.getItem('parda_token')||'')
 const [bookings,setBookings]=useState<Booking[]>([]),[selected,setSelected]=useState<Screening|null>(null),[seats,setSeats]=useState<Seat[]>([]),[chosen,setChosen]=useState<number[]>([])
 const [hold,setHold]=useState<Booking|null>(null),[payment,setPayment]=useState<any>(null),[method,setMethod]=useState('uzcard')
 const [showAuth,setShowAuth]=useState(false),[mode,setMode]=useState<'login'|'register'>('login'),[showHistory,setShowHistory]=useState(false),[showAdmin,setShowAdmin]=useState(false)
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 useEffect(()=>{document.documentElement.dataset.theme=theme;localStorage.setItem('parda_theme',theme)},[theme])
 const headers=useMemo(()=>authHeaders(token),[token])
 async function loadMovies(){const r=await fetch(`${API}/api/movies?category=${category}`);if(!r.ok)throw Error('Kino katalogini yuklab bo‘lmadi');setMovies(await r.json())}
 async function loadHistory(t=token){if(!t)return;const r=await fetch(`${API}/api/bookings`,{headers:authHeaders(t)});if(r.ok)setBookings(await r.json())}
 useEffect(()=>{if(!API){setError('Backend API ulanmagan. Vercel sozlamalarida VITE_API_URL ni kiriting.');return}let live=true;fetch(`${API}/api/movies?category=${category}`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>live&&setMovies(x)).catch(()=>live&&setError('Katalogni yuklab bo‘lmadi. Backend xizmatini tekshiring.'));return()=>{live=false}},[category])
 useEffect(()=>{if(!API||category==='upcoming')return;let live=true;fetch(`${API}/api/screenings?date=${day}`,{cache:"no-store"}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>live&&setScreenings(x)).catch(()=>live&&setError('Seanslarni yuklab bo‘lmadi.'));return()=>{live=false}},[day,category])
 useEffect(()=>{if(token&&API){fetch(`${API}/api/auth/me`,{headers:authHeaders(token)}).then(r=>r.ok?r.json():Promise.reject()).then(x=>setUser(x)).catch(()=>{localStorage.removeItem('parda_token');setToken('')});void loadHistory(token)}},[])
 const filtered=movies.filter(m=>m.title.toLocaleLowerCase().includes(query.toLocaleLowerCase()))
 const total=seats.filter(s=>chosen.includes(s.id)).reduce((n,s)=>n+Number(s.price),0)
 async function openSeats(s:Screening){setSelected(s);setChosen([]);setError('');setBusy(true);try{const r=await fetch(`${API}/api/screenings/${s.id}/seats`);const p=await r.json();if(!r.ok)throw Error(p.detail||'Joylar yuklanmadi');setSeats(p.seats)}catch(e){setError(e instanceof Error?e.message:'Xatolik')}finally{setBusy(false)}}
 async function bookSeats(){if(!user){setMode('login');setShowAuth(true);return}if(!selected||!chosen.length)return;setBusy(true);setError('');try{const r=await fetch(`${API}/api/bookings`,{method:'POST',headers,body:JSON.stringify({screening_id:selected.id,seat_ids:chosen})});const b=await r.json();if(!r.ok){if(r.status===409){const fresh=await fetch(`${API}/api/screenings/${selected.id}/seats`);if(fresh.ok)setSeats((await fresh.json()).seats)}throw Error(b.detail||'Joylar band qilinmadi')}setHold(b);setPayment(null);setSelected(null)}catch(e){setError(e instanceof Error?e.message:'Band qilishda xatolik')}finally{setBusy(false)}}
 async function startPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!hold)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);try{const r=await fetch(`${API}/api/bookings/${hold.id}/payment`,{method:'POST',headers,body:JSON.stringify({method,phone:f.get('phone')})});const p=await r.json();if(!r.ok)throw Error(p.detail||'SMS yuborilmadi');setPayment(p)}catch(e){setError(e instanceof Error?e.message:'SMS tasdiqlash boshlandi')}finally{setBusy(false)}}
 async function verify(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!hold||!payment)return;setBusy(true);setError('');try{const code=String(new FormData(e.currentTarget).get('code'));const r=await fetch(`${API}/api/payments/${payment.payment_id}/verify`,{method:'POST',headers,body:JSON.stringify({code})});const p=await r.json();if(!r.ok)throw Error(p.detail||'Kod tasdiqlanmadi');setHold(null);setPayment(null);setNotice('Buyurtma tasdiqlandi. Bu demo to‘lov: hech qanday pul yechilmadi.');void loadHistory()}catch(e){setError(e instanceof Error?e.message:'Kod xato')}finally{setBusy(false)}}
 async function release(){if(!hold)return;setBusy(true);try{await fetch(`${API}/api/bookings/${hold.id}/status`,{method:'PATCH',headers,body:JSON.stringify({status:'cancelled'})});setHold(null);setPayment(null)}finally{setBusy(false)}}
 async function authenticate(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const f=new FormData(e.currentTarget);try{if(mode==='register'){const reg=await fetch(`${API}/api/auth/register`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({nickname:f.get('nickname'),email:f.get('email'),password:f.get('password')})});if(!reg.ok)throw Error((await reg.json()).detail||'Ro‘yxatdan o‘tib bo‘lmadi')}const r=await fetch(`${API}/api/auth/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:f.get('email'),password:f.get('password')})});const a=await r.json();if(!r.ok)throw Error(a.detail||'Kirish amalga oshmadi');localStorage.setItem('parda_token',a.access_token);setToken(a.access_token);const me=await fetch(`${API}/api/auth/me`,{headers:authHeaders(a.access_token)});setUser(await me.json());await loadHistory(a.access_token);setShowAuth(false)}catch(e){setError(e instanceof Error?e.message:'Kirish amalga oshmadi')}finally{setBusy(false)}}
 async function cancel(b:Booking){if(!confirm('Buyurtmani bekor qilasizmi?'))return;const r=await fetch(`${API}/api/bookings/${b.id}/status`,{method:'PATCH',headers,body:JSON.stringify({status:'cancelled'})});if(r.ok)void loadHistory()}
 function signOut(){localStorage.removeItem('parda_token');setToken('');setUser(null);setBookings([]);setShowHistory(false)}
 if(!API)return <div className="setup-screen"><Film size={34}/><h1>Parda Cinema</h1><p>Sayt umumiy SQL bazaga ulangan backendni kutmoqda.</p><p>Vercel: <code>VITE_API_URL</code> ni backend manziliga sozlang.</p><button onClick={()=>location.reload()}>Qayta tekshirish</button></div>
 return <div className="app-shell" id="top">
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><Film size={19}/></span><span>PARDA<span className="brand-period">.</span></span></a><nav className="main-nav"><a href="#films">Kinolar</a><a href="#schedule">Seanslar</a><span className="location-label"><MapPin size={15}/> Toshkent</span></nav><div className="top-actions"><button className="theme-toggle" aria-label="Mavzuni almashtirish" onClick={()=>setTheme(theme==='light'?'dark':'light')}>{theme==='light'?<Moon size={18}/>:<Sun size={18}/>}</button>{user?<><button className="account-button" onClick={()=>setShowHistory(true)}><span className="account-avatar">{user.nickname[0]?.toUpperCase()}</span>{user.nickname}</button>{user.role==='admin'&&<button className="signin-button" onClick={()=>setShowAdmin(true)}>Admin</button>}</>:<button className="signin-button" onClick={()=>{setMode('login');setShowAuth(true)}}><UserRound size={16}/> Kirish</button>}</div></header>
  <main><section className="hero"><div className="hero-copy"><span className="eyebrow">TOSHKENT · KINO DASTURI</span><h1>Yaxshi film.<br/><em>Yaxshi oqshom.</em></h1><p>Filmni tanlang, zal xaritasidan o‘rningizni belgilang. Buyurtmangiz tasdiqlangach, joy siz uchun band bo‘ladi.</p><a className="button-primary" href="#films">Dastur bilan tanishish <Ticket size={16}/></a><div className="hero-details"><span><ShieldCheck size={15}/> Xavfsiz buyurtma</span><span><Clock3 size={15}/> 10 daqiqalik joy saqlash</span></div></div><div className="hero-art"><div className="hero-orbit orbit-one"/><div className="hero-orbit orbit-two"/><div className="hero-poster"><span className="poster-topline">PARDA CINEMA · TOSHKENT</span><span className="poster-title">KINOLAR<br/>VAQTIDAN<br/>BOSHLANADI</span><span className="poster-foot">BUGUNGI DASTUR</span></div><div className="hero-ticket"><span><Ticket size={17}/> KECHKI SEANS</span><b>Yaxshi joylar sizni kutmoqda</b><small>Joyni o‘zingiz tanlang</small></div></div></section>
  <div className="trust-strip"><span><Film size={16}/> Haqiqiy kino katalogi</span><i/><span><Armchair size={16}/> Interaktiv zal xaritasi</span><i/><span><Clock3 size={16}/> Toshkent vaqti</span><b>UZS · ASIA/TASHKENT</b></div>
  <section className="programme-section" id="films"><div className="section-head"><div><h2>{category==='now_playing'?'Ekranda':'Tez kunda'}</h2><div className="catalog-switch"><button className={category==='now_playing'?'catalog-active':''} onClick={()=>setCategory('now_playing')}>Namoyishda</button><button className={category==='upcoming'?'catalog-active':''} onClick={()=>setCategory('upcoming')}>Premyeralar</button></div></div><label className="search-box"><Search size={16}/><input value={query} placeholder="Film qidirish" onChange={e=>setQuery(e.target.value)}/></label></div>
   {category==='now_playing'&&<div className="date-rail" id="schedule"><div className="date-label"><CalendarDays size={17}/><span>SEANS KUNI</span></div>{days.map(k=><button key={k} onClick={()=>setDay(k)} className={`date-chip ${day===k?'date-current':''}`}><small>{stamp(`${k}T12:00:00+05:00`,{weekday:'short'})}</small><b>{stamp(`${k}T12:00:00+05:00`,{day:'numeric'})}</b><small>{stamp(`${k}T12:00:00+05:00`,{month:'short'})}</small></button>)}</div>}
   {error&&<div className="inline-alert"><span>{error}</span><button onClick={()=>setError('')}><X size={15}/></button></div>}
   <div className="movie-list">{filtered.map((m,i)=>{const shows=screenings.filter(s=>Number(s.movie_id)===Number(m.id));return <article className="movie-row" key={m.id}><div className={`movie-art poster-${i%6}`} style={m.poster_url?{backgroundImage:`linear-gradient(180deg,transparent,#1119),url("${m.poster_url}")`}:undefined}>{!m.poster_url&&<span className="art-title">{m.title}</span>}<span className="art-number">{m.vote_average?`★ ${Number(m.vote_average).toFixed(1)}`:''}</span></div><div className="movie-info"><div className="movie-headline"><div><span className="movie-kicker">{m.genre}</span><h3>{m.title}</h3></div><span className="age-badge">{m.age_rating}</span></div><p>{m.synopsis}</p><div className="movie-meta"><span><Clock3 size={14}/>{m.duration_minutes?`${m.duration_minutes} daqiqa`:'Davomiyligi e’lon qilinadi'}</span><span>{m.release_date?`Premyera: ${m.release_date}`:m.language}</span>{m.vote_average&&<span>★ {Number(m.vote_average).toFixed(1)} / 10</span>}</div>{m.cast_names&&m.cast_names.length>0&&<p className="cast-line"><b>Rollarda:</b> {m.cast_names.slice(0,5).join(' · ')}</p>}{m.trailer_key&&<a className="trailer-link" href={`https://www.youtube-nocookie.com/embed/${m.trailer_key}`} target="_blank" rel="noreferrer">▶ Treyler</a>}{category==='upcoming'?<p className="premiere-note">Chiqish sanasi: {m.release_date||'tez orada'} · Seanslar e’lon qilinadi</p>:<><div className="screening-head"><b>SEANSLAR</b><span>{stamp(`${day}T12:00:00+05:00`,{weekday:'long',day:'numeric',month:'long'})}</span></div>{shows.length?<div className="screening-list">{shows.map(s=><button key={s.id} className="screening-chip" onClick={()=>void openSeats(s)}><b>{stamp(s.starts_at,{hour:'2-digit',minute:'2-digit'})}</b><small>{s.auditorium_name} · {s.format_type}</small></button>)}</div>:<div className="no-showings">Bu sanada seans yo‘q. Boshqa sanani tanlang.</div>}</>}</div></article>})}{!filtered.length&&<div className="empty-state"><Film size={25}/><b>Bu yerda hozircha film yo‘q</b><span>{category==='upcoming'?'Premyera sanalari katalog yangilangach chiqadi.':'Boshqa sana yoki film nomini tanlang.'}</span></div>}</div>
  </section><section className="how-section"><h2>Uch qadamda <em>tayyor.</em></h2><div className="how-grid"><article><b>01</b><Ticket/><h3>Film va seans</h3><p>Repertuardan film va sizga qulay vaqtni tanlang.</p></article><article><b>02</b><Armchair/><h3>O‘rindiqlar</h3><p>Zal rejasidan bo‘sh joylarni tanlang.</p></article><article><b>03</b><Check/><h3>SMS tasdiqlash</h3><p>Kod tasdiqlangach buyurtma SQL bazada qayd etiladi. Demo to‘lov pul yechmaydi.</p></article></div></section></main>
  <footer className="footer"><a className="brand" href="#top"><span className="brand-mark"><Film size={18}/></span><span>PARDA<span className="brand-period">.</span></span></a><span>UZS · ASIA/TASHKENT</span><span>This product uses the TMDB API but is not endorsed or certified by TMDB.</span><a href="https://www.themoviedb.org/" target="_blank" rel="noreferrer">TMDB</a></footer>

  {selected&&<div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><section className="seat-dialog" role="dialog" aria-modal="true"><header className="dialog-header"><div><h2>{selected.movie_title}</h2><p>{stamp(selected.starts_at,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})} · {selected.cinema_name} · {selected.auditorium_name} · {selected.format_type}</p></div><button className="icon-button" onClick={()=>setSelected(null)}><X/></button></header>{busy?<div className="loading-box">Zal xaritasi yuklanmoqda…</div>:<><div className="seat-legend"><span>Bo‘sh</span><span>Tanlangan</span><span>Band</span><span>Premium</span></div><div className="screen-label"><span/> EKRAN <span/></div><div className="seat-map">{Array.from(new Set(seats.map(s=>s.row_label))).map(row=><div className="seat-row" key={row}><b>{row}</b>{seats.filter(s=>s.row_label===row).map(s=><button key={s.id} disabled={!s.available} title={`${row}${s.seat_number} · ${money(s.price)}`} className={`seat ${!s.available?'seat-taken':chosen.includes(s.id)?'seat-selected':s.seat_type==='premium'?'seat-premium':'seat-free'}`} onClick={()=>setChosen(old=>chosen.includes(s.id)?old.filter(x=>x!==s.id):old.length<8?[...old,s.id]:old)}>{s.seat_number}</button>)}<b>{row}</b></div>)}</div><div className="seat-dialog-bottom"><div className="selection-copy"><b>{seats.filter(s=>chosen.includes(s.id)).map(s=>`${s.row_label}${s.seat_number}`).join(', ')||'Joy tanlang (ko‘pi bilan 8 ta)'}</b><span>{chosen.length} ta o‘rindiq</span></div><div className="selection-action"><strong>{money(total)}</strong><button className="button-primary" disabled={!chosen.length||busy} onClick={()=>void bookSeats()}>{user?'Joylarni band qilish':'Kirish va davom etish'} <Ticket size={16}/></button></div></div></>}</section></div>}
  {hold&&<div className="modal-scrim"><section className="confirm-dialog" role="dialog" aria-modal="true"><button className="icon-button confirm-close" onClick={()=>void release()}><X/></button><div className="confirm-icon"><Ticket size={25}/></div><h2>{payment?'SMS kodini kiriting':'Buyurtma tafsilotlari'}</h2><p>{payment?'Telefoningizga yuborilgan 4 xonali tasdiqlash kodini yozing.':'Bu sinov to‘lovi: bank kartangizdan pul yechilmaydi.'}</p><div className="confirm-summary"><div><span>FILM</span><b>{hold.movie_title}</b></div><div><span>VAQT</span><b>{stamp(hold.starts_at,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</b></div><div><span>JOY</span><b>{hold.seats.join(', ')}</b></div><div><span>JAMI</span><b>{money(hold.total_price)}</b></div></div><p className="hold-countdown"><Clock3 size={15}/> Joylar 10 daqiqa saqlanadi</p>{error&&<p className="dialog-error">{error}</p>}{!payment?<form onSubmit={e=>void startPayment(e)} className="checkout-form"><label>Karta turi<select value={method} onChange={e=>setMethod(e.target.value)}><option value="uzcard">Uzcard</option><option value="humo">Humo</option><option value="visa">Visa</option><option value="mastercard">Mastercard</option></select></label><label>Karta egasining telefoni<input name="phone" type="tel" required pattern="\+[1-9][0-9]{7,14}" placeholder="+998901234567"/></label><small>Karta raqami va CVV so‘ralmaydi. Bu demo to‘lovi, haqiqiy pul olinmaydi.</small><button className="button-primary confirm-primary" disabled={busy}>SMS kodini yuborish <Ticket size={16}/></button></form>:<form onSubmit={e=>void verify(e)} className="checkout-form"><p>Usul: {method.toUpperCase()} · {payment.phone_masked}</p>{payment.demo_mode&&<div className="demo-code-note">SMS demo kodi: <b>{payment.demo_code}</b></div>}<label>4 xonali kod<input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={4} pattern="[0-9]{4}" required placeholder="0000"/></label><button className="button-primary confirm-primary" disabled={busy}>{busy?'Tekshirilmoqda…':'Tasdiqlash'} <Check size={16}/></button></form>}<button className="release-link" onClick={()=>void release()} disabled={busy}>Bekor qilish va joylarni bo‘shatish</button></section></div>}
  {showAuth&&<div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&setShowAuth(false)}><section className="auth-dialog" role="dialog" aria-modal="true"><button className="icon-button auth-close" onClick={()=>setShowAuth(false)}><X/></button><span className="brand-mark auth-mark"><Film/></span><h2>{mode==='login'?'Xush kelibsiz':'Hisob yarating'}</h2><p>Hisob va buyurtmalar SQL bazada saqlanadi.</p><form onSubmit={e=>void authenticate(e)}>{mode==='register'&&<label>Nickname<input name="nickname" required minLength={2} maxLength={40} pattern="[A-Za-z0-9_.-]+" autoComplete="nickname" placeholder="kino_sevar"/></label>}<label>Email<input name="email" type="email" required autoComplete="email" placeholder="siz@example.com"/></label><label>Parol<input name="password" type="password" required minLength={10} autoComplete={mode==='login'?'current-password':'new-password'} placeholder="Kamida 10 belgi"/></label>{error&&<p className="dialog-error">{error}</p>}<button className="button-primary auth-submit" disabled={busy}>{busy?'Kuting…':mode==='login'?'Kirish':'Hisob yaratish'}</button></form><div className="auth-switch">{mode==='login'?'Hisobingiz yo‘qmi?':'Hisobingiz bormi?'} <button onClick={()=>{setError('');setMode(mode==='login'?'register':'login')}}>{mode==='login'?'Ro‘yxatdan o‘tish':'Kirish'}</button></div><small className="auth-security"><ShieldCheck size={14}/> Parol shifrlangan holda saqlanadi</small></section></div>}
  {showHistory&&<div className="modal-scrim" onMouseDown={e=>e.target===e.currentTarget&&setShowHistory(false)}><aside className="history-drawer"><header><h2>Buyurtmalarim</h2><button className="icon-button" onClick={()=>setShowHistory(false)}><X/></button></header><p className="history-greeting">Salom, {user?.nickname}</p>{bookings.length===0?<div className="empty-state"><Ticket/><b>Hozircha buyurtma yo‘q</b><span>Film tanlab joy band qiling.</span></div>:<div className="booking-history">{bookings.map(b=><article className="history-card" key={b.id}><div className="history-card-top"><span className={`status-mark status-${b.status}`}/><b>{({pending:'Kutilmoqda',confirmed:'Tasdiqlangan',cancelled:'Bekor qilingan',completed:'Yakunlangan'} as Record<string,string>)[b.status]||b.status}</b></div><h3>{b.movie_title}</h3><p>{b.cinema_name} · {b.auditorium_name}</p><div className="history-details"><span>{stamp(b.starts_at,{weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'})}</span><span>{b.seats.join(', ')}</span><b>{money(b.total_price)}</b></div>{b.status==='confirmed'&&<button className="cancel-booking" onClick={()=>void cancel(b)}>Bekor qilish</button>}</article>)}</div>}<button className="signout" onClick={signOut}>Tizimdan chiqish</button></aside></div>}
  {notice&&<div className="modal-scrim"><section className="confirm-dialog"><div className="confirm-icon"><Check/></div><h2>Muvaffaqiyatli!</h2><p>{notice}</p><button className="button-primary" onClick={()=>{setNotice('');void loadHistory()}}>Tushunarli</button></section></div>}
  {showAdmin&&<Admin api={API} token={token} onClose={()=>setShowAdmin(false)} onSync={async()=>{await loadMovies();setNotice('TMDB film katalogi yangilandi.')}}/>}
 </div>
}

function Admin({api,token,onClose,onSync}:{api:string;token:string;onClose:()=>void;onSync:()=>void}){
 const [tab,setTab]=useState<'schedule'|'halls'|'bookings'|'catalog'>('schedule'),[busy,setBusy]=useState(false),[message,setMessage]=useState('')
 const [movies,setMovies]=useState<Movie[]>([]),[halls,setHalls]=useState<any[]>([]),[screenings,setScreenings]=useState<Screening[]>([]),[bookings,setBookings]=useState<Booking[]>([])
 async function refresh(){const h=authHeaders(token);const [m,r,s,b]=await Promise.all([fetch(`${api}/api/movies`,{headers:h}),fetch(`${api}/api/cinemas`,{headers:h}),fetch(`${api}/api/screenings?date=${today}`,{headers:h}),fetch(`${api}/api/bookings`,{headers:h})]);if(m.ok)setMovies(await m.json());if(r.ok)setHalls(await r.json());if(s.ok)setScreenings(await s.json());if(b.ok)setBookings(await b.json())}
 useEffect(()=>{void refresh().catch(()=>setMessage('Boshqaruv ma’lumotlari yuklanmadi.'))},[])
 async function submit(e:FormEvent<HTMLFormElement>,path:string,success:string,convert:(f:FormData)=>unknown){e.preventDefault();const form=e.currentTarget;setBusy(true);setMessage('');try{const f=new FormData(form);const r=await fetch(`${api}${path}`,{method:'POST',headers:authHeaders(token),body:JSON.stringify(convert(f))});const d=await r.json();if(!r.ok)throw Error(d.detail||'Saqlab bo‘lmadi');setMessage(success);form.reset();await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Xatolik')}finally{setBusy(false)}}
 async function changeStatus(b:Booking,status:string){setBusy(true);try{const r=await fetch(`${api}/api/bookings/${b.id}/status`,{method:'PATCH',headers:authHeaders(token),body:JSON.stringify({status})});const d=await r.json();if(!r.ok)throw Error(d.detail||'Holat o‘zgarmadi');await refresh()}catch(e){setMessage(e instanceof Error?e.message:'Xatolik')}finally{setBusy(false)}}
 async function sync(){setBusy(true);setMessage('');try{const r=await fetch(`${api}/api/catalog/sync`,{method:'POST',headers:authHeaders(token)});const d=await r.json();if(!r.ok)throw Error(d.detail||'TMDB sinxronlash amalga oshmadi');setMessage(`${d.imported_now_playing} ta namoyishdagi va ${d.imported_upcoming} ta premyera olindi.`);await refresh();onSync()}catch(e){setMessage(e instanceof Error?e.message:'Xatolik')}finally{setBusy(false)}}
 const nav:[typeof tab,string][]=[['schedule','Seanslar'],['halls','Zallar'],['bookings','Buyurtmalar'],['catalog','Film katalogi']]
 return <div className="admin-scrim"><section className="admin-dialog"><header className="admin-top"><b>PARDA · KINO BOSHQARUVI</b><button className="icon-button" onClick={onClose}><X/></button></header><div className="admin-body"><aside className="admin-nav"><p>BOSHQARUV</p>{nav.map(([key,label])=><button key={key} className={tab===key?'admin-active':''} onClick={()=>setTab(key)}>{label}</button>)}</aside><main className="admin-content"><h2>{nav.find(x=>x[0]===tab)?.[1]}</h2>{message&&<p className="admin-note">{message}</p>}
 {tab==='catalog'&&<div className="admin-catalog"><p>TMDB’dan hozirgi va yaqin premyeradagi film, aktyor, reyting va treyler ma’lumotlarini yangilang.</p><button className="button-primary" disabled={busy} onClick={()=>void sync()}>{busy?'Yangilanmoqda…':'TMDB katalogini yangilash'}</button><p>{movies.length} ta film bazada.</p></div>}
 {tab==='halls'&&<div className="admin-grid"><form className="admin-form" onSubmit={e=>void submit(e,'/api/cinemas','Zal va o‘rindiqlar xaritasi yaratildi.',f=>({name:f.get('name'),cinema_name:f.get('cinema'),city:'Toshkent',address:f.get('address'),timezone:'Asia/Tashkent',row_count:Number(f.get('rows')),seats_per_row:Number(f.get('columns')),formats:String(f.get('formats')).split(',').map(x=>x.trim())}))}><h3>Yangi zal</h3><label>Kinoteatr nomi<input name="cinema" required/></label><label>Zal nomi<input name="name" required/></label><label>Manzil<input name="address" required/></label><div className="admin-form-row"><label>Qatorlar<input name="rows" type="number" min="1" max="26" defaultValue="8" required/></label><label>Qatordagi joylar<input name="columns" type="number" min="1" max="30" defaultValue="12" required/></label></div><label>Formatlar<input name="formats" defaultValue="2D" placeholder="2D,3D,IMAX" required/></label><button className="button-primary" disabled={busy}>Zalni yaratish</button></form><div className="admin-catalog"><h3>Mavjud zallar</h3>{halls.map(h=><article key={h.id}><Armchair/><div><b>{h.cinema_name} · {h.name}</b><small>{h.seat_count} joy · {(h.formats||[]).join(', ')}</small></div></article>)}</div></div>}
 {tab==='schedule'&&<div className="admin-grid"><form className="admin-form" onSubmit={e=>void submit(e,'/api/screenings','Seans jadvalga qo‘shildi.',f=>({movie_id:Number(f.get('movie')),auditorium_id:Number(f.get('hall')),starts_at:new Date(`${f.get('date')}T${f.get('time')}:00+05:00`).toISOString(),base_price:Number(f.get('price')),premium_surcharge:Number(f.get('extra')),format_type:f.get('format')}))}><h3>Yangi seans</h3><label>Film<select name="movie" required>{movies.filter(m=>m.active&&m.catalog_status!=='upcoming').map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><label>Zal<select name="hall" required>{halls.map(h=><option key={h.id} value={h.id}>{h.cinema_name} · {h.name}</option>)}</select></label><div className="admin-form-row"><label>Sana<input name="date" type="date" min={today} defaultValue={today} required/></label><label>Vaqt<input name="time" type="time" defaultValue="19:00" required/></label></div><label>Format<select name="format"><option>2D</option><option>3D</option><option>IMAX</option></select></label><div className="admin-form-row"><label>Chipta (UZS)<input name="price" type="number" min="0" defaultValue="30000" required/></label><label>Premium qo‘shimcha<input name="extra" type="number" min="0" defaultValue="10000" required/></label></div><button className="button-primary" disabled={busy||!movies.length||!halls.length}>Seans yaratish</button></form><div className="admin-catalog"><h3>Bugungi seanslar · {screenings.length}</h3>{screenings.map(s=><article key={s.id}><Film/><div><b>{s.movie_title}</b><small>{stamp(s.starts_at,{hour:'2-digit',minute:'2-digit'})} · {s.auditorium_name} · {s.format_type}</small></div></article>)}</div></div>}
 {tab==='bookings'&&<div className="admin-bookings">{bookings.length?bookings.map(b=><article key={b.id}><div><b>{b.movie_title}</b><small>{b.seats.join(', ')} · {money(b.total_price)} · {b.status}</small></div><div>{b.status==='confirmed'&&<button onClick={()=>void changeStatus(b,'completed')} disabled={busy}>Yakunlash</button>}{['pending','confirmed'].includes(b.status)&&<button onClick={()=>void changeStatus(b,'cancelled')} disabled={busy}>Bekor qilish</button>}</div></article>):<p>Buyurtmalar hali yo‘q.</p>}</div>}
 </main></div></section></div>
}
