import { useEffect, useMemo, useState } from 'react'
import { ArrowLeft, ArrowRight, CalendarDays, ChevronLeft, ChevronRight, ExternalLink, Film, Search } from 'lucide-react'

type Lang='uz'|'en'|'ru'
type FilmItem={id:number;title:string;age_rating:string;language:string;poster_url:string;release_date:string|null;catalog_status:'now_playing'|'upcoming';format_type:string;cinematica_url:string}
type Show={id:number;date:string;time:string;cinema_name:string;hall_name:string;hall_type:'standard'|'vip';price:string|number|null;booking_url:string}
const words={
 uz:{playing:'Hozir kinoda',upcoming:'Tez kunda',search:'Film qidirish',release:'Premyera sanasi',language:'Namoyish tili',format:'Format',showtimes:'Seanslar',chooseDate:'Sanani tanlang',hall:'Zal turi',all:'Barcha zallar',standard:'Standard',vip:'VIP',tickets:'Chipta olish',none:'Bu film uchun hozircha seans e’lon qilinmagan.',external:'Joy tanlash va to‘lov Cinematica’da davom etadi.',back:'Kinolarga qaytish',prev:'Oldingi',next:'Keyingi',page:'Sahifa',loading:'Repertuar yuklanmoqda…',error:'Kinolar ro‘yxatini yuklab bo‘lmadi.'},
 en:{playing:'Now in cinemas',upcoming:'Coming soon',search:'Search films',release:'Release date',language:'Audio language',format:'Format',showtimes:'Showtimes',chooseDate:'Choose a date',hall:'Hall type',all:'All halls',standard:'Standard',vip:'VIP',tickets:'Get tickets',none:'No showtimes have been published for this film yet.',external:'Seat selection and secure payment continue on Cinematica.',back:'Back to films',prev:'Previous',next:'Next',page:'Page',loading:'Loading showtimes…',error:'Could not load the movie list.'},
 ru:{playing:'Сейчас в кино',upcoming:'Скоро',search:'Поиск фильмов',release:'Дата премьеры',language:'Язык показа',format:'Формат',showtimes:'Сеансы',chooseDate:'Выберите дату',hall:'Тип зала',all:'Все залы',standard:'Стандарт',vip:'VIP',tickets:'Купить билет',none:'Сеансы для этого фильма пока не опубликованы.',external:'Выбор мест и безопасная оплата продолжатся на Cinematica.',back:'Назад к фильмам',prev:'Назад',next:'Далее',page:'Страница',loading:'Загружаем сеансы…',error:'Не удалось загрузить фильмы.'}
}
const dateLabel=(iso:string,lang:Lang,options:Intl.DateTimeFormatOptions)=>new Intl.DateTimeFormat(lang==='uz'?'uz-UZ':lang==='ru'?'ru-RU':'en-US',{...options,timeZone:'Asia/Tashkent'}).format(new Date(`${iso}T12:00:00+05:00`))
const price=(value:string|number|null)=>value==null?'':`${new Intl.NumberFormat('uz-UZ').format(Number(value))} so'm`

export default function CinemaCatalog({api,lang}:{api:string;lang:Lang}){
 const t=(key:keyof typeof words.en)=>words[lang][key]
 const [category,setCategory]=useState<'now_playing'|'upcoming'>('now_playing')
 const [movies,setMovies]=useState<FilmItem[]>([]),[featured,setFeatured]=useState<FilmItem[]>([])
 const [query,setQuery]=useState(''),[page,setPage]=useState(1),[carousel,setCarousel]=useState(0)
 const [movie,setMovie]=useState<FilmItem|null>(null),[shows,setShows]=useState<Show[]>([]),[day,setDay]=useState(''),[hall,setHall]=useState<'all'|'standard'|'vip'>('all')
 const [loading,setLoading]=useState(true),[loadingShows,setLoadingShows]=useState(false),[error,setError]=useState('')
 useEffect(()=>{let live=true;setLoading(true);setError('');fetch(`${api}/api/cinematica/movies?category=${category}`).then(r=>{if(!r.ok)throw Error();return r.json()}).then((items:FilmItem[])=>{if(!live)return;setMovies(items);if(category==='now_playing')setFeatured(items)}).catch(()=>live&&setError(t('error'))).finally(()=>live&&setLoading(false));return()=>{live=false}},[api,category,lang])
 useEffect(()=>{if(featured.length<2)return;const timer=setInterval(()=>setCarousel(index=>(index+1)%featured.length),6500);return()=>clearInterval(timer)},[featured.length])
 useEffect(()=>{if(!movie)return;let live=true;setLoadingShows(true);setShows([]);setDay('');setHall('all');fetch(`${api}/api/cinematica/movies/${movie.id}/screenings`).then(r=>{if(!r.ok)throw Error();return r.json()}).then((items:Show[])=>{if(!live)return;setShows(items);if(items.length)setDay(items[0].date)}).catch(()=>live&&setShows([])).finally(()=>live&&setLoadingShows(false));return()=>{live=false}},[api,movie?.id])
 const filtered=useMemo(()=>movies.filter(m=>m.title.toLocaleLowerCase().includes(query.trim().toLocaleLowerCase())),[movies,query])
 const pageSize=12,totalPages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize)
 const activeFeature=featured.length?featured[carousel%featured.length]:null
 const dates=[...new Set(shows.map(s=>s.date))],todayShows=shows.filter(s=>s.date===day&&(hall==='all'||s.hall_type===hall))
 function selectMovie(item:FilmItem){setMovie(item);setError('');window.history.replaceState(null,'',`#movie-${item.id}`);document.getElementById('films')?.scrollIntoView({behavior:'smooth'})}
 function closeMovie(){setMovie(null);setShows([]);window.history.replaceState(null,'','#films')}
 return <>
  <section className="film-carousel" aria-label={t('playing')}>
   {activeFeature?<><div className="carousel-backdrop" style={{backgroundImage:`linear-gradient(90deg,var(--paper) 4%,color-mix(in srgb,var(--paper) 84%,transparent) 45%,transparent 100%),linear-gradient(0deg,var(--paper),transparent 48%),url("${activeFeature.poster_url}")`}}/><div className="carousel-content"><span className="carousel-kicker">PARDA CINEMA · {t('playing')}</span><h1>{activeFeature.title}</h1><div className="carousel-meta"><span className="age-badge">{activeFeature.age_rating}</span><span>{t('release')}: {activeFeature.release_date||'—'}</span><span>{activeFeature.language}</span></div><button className="carousel-cta" onClick={()=>selectMovie(activeFeature)}>{t('showtimes')} <ArrowRight size={16}/></button><div className="carousel-controls"><button aria-label={t('prev')} onClick={()=>setCarousel(i=>(i-1+featured.length)%featured.length)}><ChevronLeft/></button><span>{String(carousel+1).padStart(2,'0')} / {String(featured.length).padStart(2,'0')}</span><button aria-label={t('next')} onClick={()=>setCarousel(i=>(i+1)%featured.length)}><ChevronRight/></button></div></div><button className="carousel-poster" onClick={()=>selectMovie(activeFeature)} aria-label={`${activeFeature.title} — ${t('showtimes')}`}><img src={activeFeature.poster_url} alt=""/></button></>:<div className="carousel-empty"><Film/><span>{loading?t('loading'):t('error')}</span></div>}
  </section>
  <section className="programme-section compact-programme" id="films">
   <div className="section-head"><div><h2>{category==='now_playing'?t('playing'):t('upcoming')}</h2><div className="catalog-switch"><button className={category==='now_playing'?'catalog-active':''} onClick={()=>{setCategory('now_playing');setPage(1)}}>{t('playing')}</button><button className={category==='upcoming'?'catalog-active':''} onClick={()=>{setCategory('upcoming');setPage(1)}}>{t('upcoming')}</button></div></div><label className="search-box"><Search size={16}/><input value={query} placeholder={t('search')} onChange={e=>{setQuery(e.target.value);setPage(1)}}/></label></div>
   {error&&<div className="inline-alert"><span>{error}</span></div>}
   {movie?<div className="movie-detail-panel"><button className="detail-back" onClick={closeMovie}><ArrowLeft size={16}/>{t('back')}</button><div className="detail-heading"><img src={movie.poster_url} alt=""/><div><h2>{movie.title}</h2><div className="detail-facts"><span className="age-badge">{movie.age_rating}</span><span>{t('release')}: {movie.release_date||'—'}</span><span>{t('language')}: {movie.language}</span><span>{t('format')}: {movie.format_type}</span></div><a className="cinematica-source" href={movie.cinematica_url} target="_blank" rel="noreferrer">Cinematica <ExternalLink size={13}/></a></div></div><div className="showtimes-panel"><div className="showtimes-title"><h3><CalendarDays size={19}/>{t('showtimes')}</h3><span>{t('chooseDate')}</span></div>{loadingShows?<p className="catalog-empty">{t('loading')}</p>:shows.length===0?<p className="catalog-empty">{t('none')}</p>:<><div className="detail-dates">{dates.map(date=><button key={date} className={day===date?'detail-date-active':''} onClick={()=>setDay(date)}><span>{dateLabel(date,lang,{weekday:'short'})}</span><b>{dateLabel(date,lang,{day:'numeric',month:'short'})}</b></button>)}</div><div className="detail-halls"><span>{t('hall')}</span>{(['all','standard','vip'] as const).map(type=><button key={type} className={hall===type?'detail-hall-active':''} onClick={()=>setHall(type)}>{type==='all'?t('all'):type==='vip'?t('vip'):t('standard')}</button>)}</div><div className="live-showtimes">{todayShows.map(show=><a key={show.id} href={show.booking_url} target="_blank" rel="noopener noreferrer" className="live-showtime"><span><b>{show.time}</b><small>{show.cinema_name} · {show.hall_name} · {show.hall_type==='vip'?t('vip'):t('standard')}</small></span><span className="live-showtime-buy">{show.price?price(show.price):''}<b>{t('tickets')} <ExternalLink size={13}/></b></span></a>)}{todayShows.length===0&&<p className="catalog-empty">{t('none')}</p>}</div><p className="external-booking-note">{t('external')}</p></>}</div></div>:<>
    {loading?<div className="catalog-loading">{t('loading')}</div>:filtered.length===0?<div className="catalog-empty">{category==='now_playing'?t('error'):t('none')}</div>:<><div className="film-grid">{visible.map(item=><button className="film-card" key={item.id} onClick={()=>selectMovie(item)}><span className="film-poster-wrap"><img src={item.poster_url} alt="" loading="lazy"/><span className="film-age">{item.age_rating}</span><span className="poster-glow"/></span><span className="film-card-title" title={item.title}>{item.title}</span></button>)}</div><nav className="film-pagination" aria-label="Film pages"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}><ChevronLeft size={16}/>{t('prev')}</button><span>{t('page')} {page} / {totalPages}</span><button disabled={page>=totalPages} onClick={()=>setPage(p=>Math.min(totalPages,p+1))}>{t('next')}<ChevronRight size={16}/></button></nav></>}
   </>}
  </section>
 </>
}
