import { useCallback, useEffect, useState, type CSSProperties, type FormEvent } from 'react'
import { Check, Clock3, CreditCard, LockKeyhole, Mail, X } from 'lucide-react'
import { useResendCountdown } from './useResendCountdown'
import { formatDateTime } from './dateFormat'

type Lang = 'uz' | 'en' | 'ru'
type Screening = {id:number; movie_title:string; starts_at:string; cinema_name:string; auditorium_name:string; available_seats:number; format_type:string; hall_type:'standard'|'vip'; base_price:number|string}
type SourceShow = {id:number; date:string; time:string; cinema_name:string; hall_name:string; hall_type:'standard'|'vip'; format_type:string; price:string|number|null; source_name?:'cinematica'|'ticketon'}
type Seat = {id:number; row_label:string; seat_number:number; seat_type:string; price:number|string; available:boolean}
type Booking = {id:number; status:string; total_price:number|string; movie_title:string; starts_at:string; cinema_name:string; auditorium_name:string; seats:string[]; seat_count:number; hold_expires_at:string|null; hold_seconds_remaining:number|null}
type Payment = {payment_id:number; reference:string; method:string; card_last4:string; email_masked:string; amount:number|string; expires_at:string; resend_available_at?:string|null; demo_mode:boolean; status?:string}

const text = {
 uz:{expiryPast:'Kartaning amal qilish muddati o‘tgan. Joriy yoki kelajakdagi sanani kiriting.',title:'Parda seanslari',sub:'Joyni tanlang, email kodi bilan chiptani tasdiqlang.',today:'Bugun',empty:'Bu kunda Parda seanslari yo‘q.',seats:'joy qoldi',choose:'Joylarni tanlash',screen:'EKRAN',available:'Bo‘sh',selected:'Tanlangan',taken:'Band',premium:'Premium',reserve:'Joylarni band qilish',signin:'Kirish va davom etish',payment:'To‘lov',summary:'Buyurtma xulosasi',method:'To‘lov usuli',card:'Karta raqami',holder:'Karta egasi',expiry:'Amal qilish muddati',cvv:'CVV',pay:'Email kodini yuborish',demo:'To‘lovni tasdiqlash • Haqiqiy pul yechilmaydi',code:'4 xonali email kodi',sent:'Tasdiqlash kodi yuborildi:',verify:'To‘lovni tasdiqlash',resend:'Kodni qayta yuborish',success:'To‘lov muvaffaqiyatli',ticket:'Chiptangiz tasdiqlandi.',close:'Yopish',back:'Orqaga',loading:'Yuklanmoqda…',noCvv:'Uzcard va Humo kartalarida CVV talab qilinmaydi.',hold:'Joylar 10 daqiqa saqlanadi.',holdRemaining:'Joylar saqlanishiga qoldi',holdExpired:'Joyni saqlash vaqti tugadi. Iltimos, joylarni qayta tanlang.',movie:'Film',cinema:'Kinoteatr',time:'Sana va vaqt',seatLabel:'Joylar',total:'Jami',error:'Xatolik yuz berdi. Qayta urinib ko‘ring.'},
 en:{expiryPast:'This card has expired. Enter the current month or a future expiry date.',title:'Parda sessions',sub:'Choose seats and confirm your ticket with an email code.',today:'Today',empty:'There are no Parda sessions on this day.',seats:'seats left',choose:'Choose seats',screen:'SCREEN',available:'Available',selected:'Selected',taken:'Taken',premium:'Premium',reserve:'Reserve seats',signin:'Sign in to continue',payment:'Payment',summary:'Booking summary',method:'Payment method',card:'Card number',holder:'Cardholder name',expiry:'Expiry date',cvv:'CVV',pay:'Send email code',demo:'Payment confirmation • No real money will be charged',code:'4 digit email code',sent:'A verification code was sent to:',verify:'Confirm payment',resend:'Resend code',success:'Payment complete',ticket:'Your ticket is confirmed.',close:'Close',back:'Back',loading:'Loading…',noCvv:'Uzcard and Humo cards do not use CVV.',hold:'Seats are held for 10 minutes.',holdRemaining:'Seat hold remaining',holdExpired:'Your seat hold expired. Please choose seats again.',movie:'Movie',cinema:'Cinema',time:'Date and time',seatLabel:'Seats',total:'Total',error:'Something went wrong. Please try again.'},
 ru:{expiryPast:'Срок действия карты истёк. Укажите текущий месяц или будущую дату.',title:'Сеансы Parda',sub:'Выберите места и подтвердите билет кодом из email.',today:'Сегодня',empty:'На этот день сеансов Parda нет.',seats:'мест осталось',choose:'Выбрать места',screen:'ЭКРАН',available:'Свободно',selected:'Выбрано',taken:'Занято',premium:'Премиум',reserve:'Забронировать места',signin:'Войти и продолжить',payment:'Оплата',summary:'Сводка заказа',method:'Способ оплаты',card:'Номер карты',holder:'Держатель карты',expiry:'Срок действия',cvv:'CVV',pay:'Отправить код на email',demo:'Подтверждение оплаты • Деньги не списываются',code:'4-значный код из email',sent:'Код подтверждения отправлен на:',verify:'Подтвердить оплату',resend:'Отправить код ещё раз',success:'Оплата завершена',ticket:'Ваш билет подтверждён.',close:'Закрыть',back:'Назад',loading:'Загрузка…',noCvv:'Для карт Uzcard и Humo CVV не требуется.',hold:'Места удерживаются 10 минут.',holdRemaining:'До окончания удержания мест',holdExpired:'Время удержания мест истекло. Выберите места снова.',movie:'Фильм',cinema:'Кинотеатр',time:'Дата и время',seatLabel:'Места',total:'Итого',error:'Что-то пошло не так. Повторите попытку.'}
}
const paymentMethods = ['uzcard','humo','visa','mastercard'] as const
type Method = typeof paymentMethods[number]
const locale = (lang:Lang) => lang === 'uz' ? 'uz-UZ' : lang === 'ru' ? 'ru-RU' : 'en-US'
const money = (value:number|string, lang:Lang) => `${new Intl.NumberFormat(locale(lang)).format(Number(value))} UZS`
const stamp = (value:string, lang:Lang) => formatDateTime(value,lang)
const headers = (token:string) => ({Authorization:`Bearer ${token}`,'Content-Type':'application/json'})
const normalizeDigits = (value:string) => value.replace(/\D/g,'')
const formatCard = (value:string) => normalizeDigits(value).slice(0,19).replace(/(.{4})/g,'$1 ').trim()
const expiryIsCurrentOrFuture = (value:string) => {
 const match = value.match(/^(\d{2})\s*\/\s*(\d{2})$/)
 if (!match) return false
 const month = Number(match[1]), year = 2000 + Number(match[2])
 const now = new Date()
 return month >= 1 && month <= 12 && year >= now.getFullYear() && year <= now.getFullYear() + 30 && (year > now.getFullYear() || month >= now.getMonth() + 1)
}
const formatExpiry = (value:string) => {const d=normalizeDigits(value).slice(0,4);return d.length>2?`${d.slice(0,2)} / ${d.slice(2)}`:d}

function useHoldCountdown(expiresAt:string|null,initialSeconds:number|null){
 const [now,setNow]=useState(Date.now())
 const [start,setStart]=useState(now)
 useEffect(()=>{const current=Date.now();setStart(current);setNow(current)},[expiresAt,initialSeconds])
 const elapsed=Math.floor((now-start)/1000)
 const secondsLeft=expiresAt?Math.max(0,(initialSeconds??0)-elapsed):0
 useEffect(()=>{if(!expiresAt)return;const timer=window.setInterval(()=>setNow(Date.now()),1000);return()=>window.clearInterval(timer)},[expiresAt])
 return {expired:Boolean(expiresAt)&&secondsLeft===0,label:`${Math.floor(secondsLeft/60)}:${String(secondsLeft%60).padStart(2,'0')}`}
}

const seatEmblem=(title:string)=>/spider/i.test(title)?'🕷️':/avengers|мстител/i.test(title)?'🛡️':/resident evil|обитель/i.test(title)?'🧟':/linkin/i.test(title)?'🎸':'✦'

export default function PardaBooking({api, token, lang, onSignIn, onConfirmed, onDismiss, movieId, movieTitle, posterUrl, sourceShow}:{api:string;token:string;lang:Lang;onSignIn:()=>void;onConfirmed:()=>void;onDismiss:()=>void;movieId:number;movieTitle:string;posterUrl:string;sourceShow:SourceShow}) {
 const t=(key:keyof typeof text.en)=>text[lang][key]
 const [resolving,setResolving]=useState(true),[error,setError]=useState('')
 const [screening,setScreening]=useState<Screening|null>(null),[seats,setSeats]=useState<Seat[]>([]),[selected,setSelected]=useState<number[]>([])
 const [booking,setBooking]=useState<Booking|null>(null),[payment,setPayment]=useState<Payment|null>(null),[method,setMethod]=useState<Method>('uzcard'),[card,setCard]=useState(''),[holder,setHolder]=useState(''),[expiry,setExpiry]=useState(''),[cvv,setCvv]=useState(''),[code,setCode]=useState(''),[busy,setBusy]=useState(false)
 const paymentCooldown=useResendCountdown()
 const hold=useHoldCountdown(booking?.hold_expires_at||null,booking?.hold_seconds_remaining??null)
 useEffect(()=>{let active=true;setResolving(true);setError('');setScreening(null);setSeats([]);const sourcePath=sourceShow.source_name==='ticketon'?`ticketon/${Math.abs(sourceShow.id)}`:`screenings/${sourceShow.id}`;fetch(`${api}/api/cinematica/movies/${movieId}/${sourcePath}/ticketing`,{method:'POST'}).then(async response=>{const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));return data}).then(async(item:Screening)=>{const response=await fetch(`${api}/api/screenings/${item.id}/seats`);const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));if(active){setScreening(item);setSeats(data.seats)}}).catch(err=>active&&setError(err instanceof Error?err.message:t('error'))).finally(()=>active&&setResolving(false));return()=>{active=false}},[api,movieId,sourceShow.id,sourceShow.source_name,lang])
 const chosenSeats=seats.filter(seat=>selected.includes(seat.id))
 const chosenTotal=chosenSeats.reduce((total,seat)=>total+Number(seat.price),0)
 const refreshSeats=useCallback(async(screeningId:number)=>{try{const response=await fetch(`${api}/api/screenings/${screeningId}/seats`);const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setSeats(data.seats)}catch(err){setError(err instanceof Error?err.message:t('error'))}},[api,lang])
 useEffect(()=>{if(!booking||!hold.expired||payment?.status==='succeeded_demo')return;setBooking(null);setPayment(null);setSelected([]);paymentCooldown.clear();setError(t('holdExpired'));if(screening)void refreshSeats(screening.id)},[booking?.id,hold.expired,payment?.status,screening?.id,refreshSeats,lang])
 const toggleSeat=(seat:Seat)=>setSelected(current=>current.includes(seat.id)?current.filter(id=>id!==seat.id):current.length>=8?current:[...current,seat.id])
 const reserve=async()=>{if(!screening)return;if(!token){onSignIn();return}if(!selected.length){setError(t('choose'));return}setBusy(true);setError('');try{const response=await fetch(`${api}/api/bookings`,{method:'POST',headers:headers(token),body:JSON.stringify({screening_id:screening.id,seat_ids:selected})});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setBooking(data)}catch(err){setError(err instanceof Error?err.message:t('error'))}finally{setBusy(false)}}
 const chooseMethod=(value:Method)=>{setMethod(value);setCvv('')}
 const startPayment=async(e:FormEvent)=>{e.preventDefault();if(!booking)return;setError('');if(!expiryIsCurrentOrFuture(expiry)){setError(t('expiryPast'));return}setBusy(true);try{const response=await fetch(`${api}/api/payments/create`,{method:'POST',headers:headers(token),body:JSON.stringify({booking_id:booking.id,method,card_number:normalizeDigits(card),cardholder_name:holder,expiry_date:expiry,cvv:cvv||null})});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setPayment(data);paymentCooldown.start(data.resend_available_at)}catch(err){setError(err instanceof Error?err.message:t('error'))}finally{setBusy(false)}}
 const resend=async()=>{if(!payment||paymentCooldown.secondsLeft)return;setBusy(true);setError('');try{const response=await fetch(`${api}/api/payments/${payment.payment_id}/resend`,{method:'POST',headers:headers(token)});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setPayment(data);paymentCooldown.start(data.resend_available_at)}catch(err){setError(err instanceof Error?err.message:t('error'))}finally{setBusy(false)}}
 const verify=async(e:FormEvent)=>{e.preventDefault();if(!payment)return;setBusy(true);setError('');try{const response=await fetch(`${api}/api/payments/${payment.payment_id}/verify`,{method:'POST',headers:headers(token),body:JSON.stringify({code})});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setBooking(data.booking);setPayment({...payment,status:'succeeded_demo'});onConfirmed()}catch(err){setError(err instanceof Error?err.message:t('error'))}finally{setBusy(false)}}
 const close=()=>{setScreening(null);setSeats([]);setSelected([]);setBooking(null);setPayment(null);paymentCooldown.clear();setCode('');setCard('');setHolder('');setExpiry('');setCvv('');setMethod('uzcard');setError('');onDismiss()}
 const hasSuccess=Boolean(payment?.status==='succeeded_demo')
 return <section className="parda-inline-booking">
  {resolving&&<p className="parda-empty">{t('loading')}</p>}
  {error&&!screening&&<div className="payment-error" role="alert">{error}<button className="payment-resend" onClick={close}>{t('back')}</button></div>}
  {screening&&<div className="modal-scrim payment-scrim" onMouseDown={event=>event.target===event.currentTarget&&close()}><section className="seat-dialog parda-seat-dialog" style={{'--seat-art':`url("${posterUrl}")`} as CSSProperties} role="dialog" aria-modal="true" aria-label={t('choose')}><header className="dialog-header"><div><span>PARDA TICKETS</span><h2>{screening.movie_title}</h2><p>{stamp(screening.starts_at,lang)} · {screening.cinema_name} · {screening.auditorium_name}</p></div><button className="icon-button" onClick={close} aria-label={t('close')}><X/></button></header><><div className="seat-legend"><span><i className="seat-dot seat-open"/>{t('available')}</span><span><i className="seat-dot seat-picked"/>{t('selected')}</span><span><i className="seat-dot seat-busy"/>{t('taken')}</span><span><i className="seat-dot seat-vip"/>{t('premium')}</span></div><div className="seat-map"><div className="screen-label">{t('screen')}</div>{[...new Set(seats.map(seat=>seat.row_label))].map(row=><div className="seat-row" key={row}><b>{row}</b>{seats.filter(seat=>seat.row_label===row).map(seat=><button key={seat.id} data-mark={seatEmblem(movieTitle)} disabled={!seat.available} className={`seat ${seat.seat_type==='premium'?'seat-premium':''} ${selected.includes(seat.id)?'seat-selected':''} ${!seat.available?'seat-taken':''}`} onClick={()=>toggleSeat(seat)} aria-pressed={selected.includes(seat.id)}>{seat.seat_number}</button>)}</div>)}</div><footer className="seat-dialog-bottom"><div className="selection-copy"><span>{t('hold')}</span><b>{chosenSeats.length?chosenSeats.map(seat=>`${seat.row_label}${seat.seat_number}`).join(', '):t('choose')}</b></div><div className="selection-action"><strong>{money(chosenTotal,lang)}</strong><button className="button-primary" disabled={busy||!selected.length} onClick={()=>void reserve()}>{busy?t('loading'):token?t('reserve'):t('signin')}</button></div></footer>{error&&<p className="payment-error" role="alert">{error}</p>}</></section></div>}
  {booking&&!payment&&<div className="modal-scrim payment-scrim"><section className="payment-dialog" role="dialog" aria-modal="true" aria-label={t('payment')}><button className="icon-button payment-close" onClick={close} aria-label={t('close')}><X/></button><div className="payment-heading"><span><LockKeyhole size={15}/> {t('demo')}</span><h2>{t('payment')}</h2><HoldTimer label={t('holdRemaining')} value={hold.label}/></div><PaymentSummary booking={booking} lang={lang} t={t}/><form className="demo-payment-form" onSubmit={event=>void startPayment(event)}><fieldset><legend>{t('method')}</legend><div className="payment-methods">{paymentMethods.map(value=><button type="button" className={method===value?'active':''} onClick={()=>chooseMethod(value)} key={value}><CreditCard size={15}/>{value}</button>)}</div></fieldset><label>{t('card')}<input value={card} inputMode="numeric" autoComplete="cc-number" placeholder="0000 0000 0000 0000" onChange={event=>setCard(formatCard(event.target.value))} required/></label><label>{t('holder')}<input value={holder} autoComplete="cc-name" maxLength={80} onChange={event=>setHolder(event.target.value)} required/></label><div className="payment-row"><label>{t('expiry')}<input value={expiry} inputMode="numeric" autoComplete="cc-exp" placeholder="MM / YY" onChange={event=>setExpiry(formatExpiry(event.target.value))} required/></label>{(method==='visa'||method==='mastercard')&&<label>{t('cvv')}<input value={cvv} inputMode="numeric" autoComplete="cc-csc" type="password" maxLength={4} onChange={event=>setCvv(normalizeDigits(event.target.value).slice(0,4))} required/></label>}</div>{(method==='uzcard'||method==='humo')&&<small>{t('noCvv')}</small>}{error&&<p className="payment-error" role="alert">{error}</p>}<button className="button-primary payment-submit" disabled={busy||hold.expired}>{busy?t('loading'):t('pay')}<Mail size={16}/></button></form></section></div>}
  {payment&&!hasSuccess&&<div className="modal-scrim payment-scrim"><section className="payment-dialog verify-dialog" role="dialog" aria-modal="true" aria-label={t('verify')}><button className="icon-button payment-close" onClick={close} aria-label={t('close')}><X/></button><div className="payment-heading"><span><Mail size={15}/> {t('demo')}</span><h2>{t('verify')}</h2><p>{t('sent')} <b>{payment.email_masked}</b></p><HoldTimer label={t('holdRemaining')} value={hold.label}/></div><PaymentSummary booking={booking!} lang={lang} t={t}/><form className="demo-payment-form" onSubmit={event=>void verify(event)}><label>{t('code')}<input className="payment-code" value={code} inputMode="numeric" autoComplete="one-time-code" maxLength={4} pattern="[0-9]{4}" placeholder="0000" onChange={event=>setCode(normalizeDigits(event.target.value).slice(0,4))} required/></label><small>{t('demo')}</small>{error&&<p className="payment-error" role="alert">{error}</p>}<button className="button-primary payment-submit" disabled={busy||hold.expired||code.length!==4}>{busy?t('loading'):t('verify')}<Check size={16}/></button></form><button className="payment-resend" onClick={()=>void resend()} disabled={busy||hold.expired||Boolean(paymentCooldown.secondsLeft)}>{paymentCooldown.secondsLeft?`${t('resend')} (${paymentCooldown.label})`:t('resend')}</button></section></div>}
  {hasSuccess&&<div className="modal-scrim payment-scrim"><section className="payment-dialog payment-success" role="dialog" aria-modal="true"><div className="payment-success-icon"><Check/></div><h2>{t('success')}</h2><p>{t('ticket')}</p><PaymentSummary booking={booking!} lang={lang} t={t}/><small>{payment!.reference}</small><button className="button-primary payment-submit" onClick={close}>{t('close')}</button></section></div>}
 </section>
}

function HoldTimer({label,value}:{label:string;value:string}){return <p className="hold-timer" role="status"><Clock3 size={15}/><span>{label}</span><b>{value}</b></p>}

function PaymentSummary({booking,lang,t}:{booking:Booking;lang:Lang;t:(key:keyof typeof text.en)=>string}){return <section className="payment-summary"><h3>{t('summary')}</h3><dl><div><dt>{t('movie')}</dt><dd>{booking.movie_title}</dd></div><div><dt>{t('cinema')}</dt><dd>{booking.cinema_name} · {booking.auditorium_name}</dd></div><div><dt>{t('time')}</dt><dd>{stamp(booking.starts_at,lang)}</dd></div><div><dt>{t('seatLabel')}</dt><dd>{booking.seats.join(', ')}</dd></div><div className="payment-total"><dt>{t('total')}</dt><dd>{money(booking.total_price,lang)}</dd></div></dl></section>}
