import { useState, type FormEvent } from 'react'
import { KeyRound, Mail, ShieldCheck, X } from 'lucide-react'

type Lang = 'uz'|'en'|'ru'
const words = {
 uz:{title:'Parolni tiklash',intro:'Email manzilingizni kiriting. Sizga 4 xonali tasdiqlash kodi yuboriladi.',email:'Email',send:'Kodni yuborish',sent:'Agar hisob mavjud bo‘lsa, kod emailga yuborildi.',newPass:'Yangi parol',code:'Email kodi',confirm:'Parolni yangilash',back:'Kirishga qaytish',success:'Parol yangilandi. Endi yangi parol bilan kiring.',resend:'Kodni qayta yuborish',error:'Xatolik yuz berdi. Qayta urinib ko‘ring.',security:'Kod 10 daqiqa amal qiladi. Yangi parol kamida 10 belgidan iborat bo‘lsin.'},
 en:{title:'Reset password',intro:'Enter your email and we will send a 4 digit verification code.',email:'Email',send:'Send code',sent:'If that account exists, a code has been sent to its email address.',newPass:'New password',code:'Email code',confirm:'Update password',back:'Back to sign in',success:'Your password has been updated. Sign in with the new password.',resend:'Resend code',error:'Something went wrong. Please try again.',security:'The code expires in 10 minutes. Your new password needs at least 10 characters.'},
 ru:{title:'Сброс пароля',intro:'Введите email. Мы отправим на него 4-значный код подтверждения.',email:'Email',send:'Отправить код',sent:'Если аккаунт существует, код отправлен на его email.',newPass:'Новый пароль',code:'Код из email',confirm:'Обновить пароль',back:'Вернуться ко входу',success:'Пароль обновлён. Войдите с новым паролем.',resend:'Отправить код ещё раз',error:'Что-то пошло не так. Повторите попытку.',security:'Код действует 10 минут. Новый пароль должен содержать минимум 10 символов.'}
}

export default function PasswordReset({api,lang,onClose}:{api:string;lang:Lang;onClose:()=>void}) {
 const t=(key:keyof typeof words.en)=>words[lang][key]
 const [email,setEmail]=useState(''),[stage,setStage]=useState<'email'|'code'|'success'>('email'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[demoCode,setDemoCode]=useState('')
 const request=async(event?:FormEvent)=>{event?.preventDefault();setBusy(true);setError('');try{const response=await fetch(`${api}/api/auth/password-reset/request`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setDemoCode(data.demo_code||'');setStage('code')}catch(reason){setError(reason instanceof Error?reason.message:t('error'))}finally{setBusy(false)}}
 const confirm=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);setBusy(true);setError('');try{const response=await fetch(`${api}/api/auth/password-reset/confirm`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,code:form.get('code'),password:form.get('password')})});const data=await response.json();if(!response.ok)throw Error(data.detail||t('error'));setStage('success')}catch(reason){setError(reason instanceof Error?reason.message:t('error'))}finally{setBusy(false)}}
 return <div className="modal-scrim" onMouseDown={event=>event.target===event.currentTarget&&onClose()}><section className="auth-dialog" role="dialog" aria-modal="true" aria-label={t('title')}><button className="icon-button auth-close" onClick={onClose} aria-label={t('back')}><X/></button><span className="brand-mark auth-mark"><KeyRound/></span><h2>{t('title')}</h2>{stage==='email'&&<><p>{t('intro')}</p><form onSubmit={event=>void request(event)}><label>{t('email')}<input type="email" value={email} onChange={event=>setEmail(event.target.value)} required autoComplete="email" placeholder="siz@example.com"/></label>{error&&<p className="dialog-error">{error}</p>}<button className="button-primary auth-submit" disabled={busy}>{busy?'…':t('send')}<Mail size={16}/></button></form></>}{stage==='code'&&<><p>{t('sent')}</p><form onSubmit={event=>void confirm(event)}><label>{t('code')}<input name="code" inputMode="numeric" autoComplete="one-time-code" maxLength={4} pattern="[0-9]{4}" required placeholder="0000"/></label><label>{t('newPass')}<input name="password" type="password" autoComplete="new-password" minLength={10} maxLength={128} required placeholder="••••••••••"/></label>{demoCode&&<div className="demo-code-note">Local test code: <b>{demoCode}</b></div>}{error&&<p className="dialog-error">{error}</p>}<button className="button-primary auth-submit" disabled={busy}>{busy?'…':t('confirm')}</button></form><button className="release-link" onClick={()=>void request()} disabled={busy}>{t('resend')}</button></>}{stage==='success'&&<p className="auth-reset-success">{t('success')}</p>}<button className="auth-switch" onClick={onClose}>{t('back')}</button><small className="auth-security"><ShieldCheck size={14}/>{t('security')}</small></section></div>
}
